Initial implementation of the package
EdisonLabs/policy-verification pull request #1
Opened 2019-02-05 13:06 UTC by jkribeiro

2019-02-06 10:14 UTC, manuee requested changes

2019-02-06 10:14 UTC, manuee commented on src/Command/PolicyVerificationCommand.php
> +     * @param string $data The data JSON value.
This param can also be a path to a json file.
```suggestion
     * @param string $data The data command option.
```

2019-02-06 10:14 UTC, manuee commented on src/Command/PolicyVerificationCommand.php
> +        throw new RuntimeException('Data parameter must be a valid JSON format');
This will be thrown also if the file passed in is not found.
```suggestion
        throw new RuntimeException('Data parameter must be a valid file or string with valid JSON format');
```

2019-02-06 10:14 UTC, manuee commented on src/Command/PolicyVerificationCommand.php
> +        $this->outputReport($input, $output);
Nit: This works, but I think just calling `outputReport()` here could be improved, how about something like this instead?
```
$policySummary = $this->report->getResultSummary();
$format = $input->getOption('format');
if ('json' == $format) {
    $output->writeln(json_encode($policySummary));
}
else if ('table' == $format) {
    $this->renderPolicySummaryAsTable($policySummary, $output);
}
else {
    // Throw exception for invalid format
}
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +                    continue;
Can we throw an error here instead?

2019-02-06 10:14 UTC, manuee commented on src/Command/PolicyVerificationCommand.php
> +    public function setPolicyCheck(AbstractPolicyCheckBase $policyCheck)
```suggestion
    public function setPolicyCheck(PolicyCheckInterface $policyCheck)
```

2019-02-06 10:14 UTC, manuee commented on src/Command/PolicyVerificationCommand.php
> +     * @param \EdisonLabs\PolicyVerification\Check\AbstractPolicyCheckBase $policyCheck The policy check object.
```suggestion
     * @param \EdisonLabs\PolicyVerification\Check\PolicyCheckInterface $policyCheck The policy check object.
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +    public function setCheck(AbstractPolicyCheckBase $policyCheck)
```suggestion
    public function setCheck(PolicyCheckInterface $policyCheck)
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +     * @param \EdisonLabs\PolicyVerification\Check\AbstractPolicyCheckBase $policyCheck The policy check object.
```suggestion
     * @param \EdisonLabs\PolicyVerification\Check\PolicyCheckInterface $policyCheck The policy check object.
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +        /** @var \EdisonLabs\PolicyVerification\Check\AbstractPolicyCheckBase $policyCheck */
```suggestion
        /** @var \EdisonLabs\PolicyVerification\Check\PolicyCheckInterface $policyCheck */
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +        /** @var \EdisonLabs\PolicyVerification\Check\AbstractPolicyCheckBase $policyCheck */
```suggestion
        /** @var \EdisonLabs\PolicyVerification\Check\PolicyCheckInterface $policyCheck */
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +        /** @var \EdisonLabs\PolicyVerification\Check\AbstractPolicyCheckBase $policyCheck */
```suggestion
        /** @var \EdisonLabs\PolicyVerification\Check\PolicyCheckInterface $policyCheck */
```

2019-02-06 10:14 UTC, manuee commented on src/Report.php
> +                if (!$policyCheck instanceof AbstractPolicyCheckBase) {
Should we be checking for PolicyCheckInterface instead?
```suggestion
                if (!$policyCheck instanceof PolicyCheckInterface) {
```

2019-02-06 11:56 UTC, jkribeiro commented on src/Command/PolicyVerificationCommand.php
> +        $this->outputReport($input, $output);
Looks good :+1:

2019-02-07 10:45 UTC, manuel-work approved these changes

2019-02-07 10:45 UTC, manuee approved these changes

2019-02-07 10:47 UTC, merged